const EVALUATION_SCHEMA_VERSION = 1

const EVALUATION_CASES = (
    (
        id=:direct_trigger,
        title="Direct PlantSimEngine authoring request",
        workspace_fixture="assets/minimal-model.jl",
        oracle=:workspace_direct_trigger,
        oracle_level=:workspace_precondition,
        prompt="Create a PlantSimEngine model with complete ports and contracts, test its kernel directly, and compose one explicit cross-object binding.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/scenario-coupling.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :inspect_available_processes,
            :validate_model,
            :validate_scenario,
            :use_public_diagnostics,
        ),
        forbidden_actions=(:edit_before_verification, :invent_scientific_metadata),
    ),
    (
        id=:indirect_dependency_trigger,
        title="Indirect request in a PlantSimEngine-dependent package",
        workspace_fixture="evaluations/fixtures/two-process-package/Project.toml",
        oracle=:workspace_plantsimengine_dependency,
        oracle_level=:workspace_precondition,
        prompt="Add a second canopy carbon-gain hypothesis beside the existing implementation, keep it generic, compare whether it can replace the current model, and put its direct tests in the package convention.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/repository-layout.md",
            "references/diagnostics.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :reuse_existing_process,
            :compare_models,
            :document_scientific_status,
        ),
        forbidden_actions=(:redeclare_dependency_process, :assume_same_process_is_drop_in),
    ),
    (
        id=:incomplete_process_request,
        title="Incomplete scientific request",
        workspace_fixture="evaluations/fixtures/two-process-package/Project.toml",
        oracle=:workspace_incomplete_request,
        oracle_level=:workspace_precondition,
        prompt="Add a maintenance-respiration model. Use the project conventions and make it runnable.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=("references/model-authoring.md",),
        required_actions=(
            :verify_loaded_package,
            :inspect_available_processes,
            :report_unresolved_science,
            :avoid_invented_units_or_defaults,
        ),
        forbidden_actions=(:declare_process_without_discovery, :invent_scientific_metadata),
    ),
    (
        id=:non_trigger_generic_julia,
        title="Unrelated Julia task",
        workspace_fixture="evaluations/fixtures/generic-julia/Project.toml",
        oracle=:workspace_generic_julia,
        oracle_level=:workspace_precondition,
        prompt="Implement and test a stable generic merge sort for vectors in this Julia package.",
        required_skills=(:kaimon_julia,),
        forbidden_skills=(:plantsimengine,),
        required_references=(),
        required_actions=(:use_kaimon_session,),
        forbidden_actions=(:read_plantsimengine_skill, :introduce_plantsimengine_dependency),
    ),
    (
        id=:wrong_environment_old_documentation,
        title="Loaded package and old documentation disagree",
        workspace_fixture="evaluations/fixtures/stale-environment/README.md",
        oracle=:workspace_stale_environment,
        oracle_level=:workspace_precondition,
        prompt="Follow the checked-out tutorial to add the model, even though Julia currently loads another PlantSimEngine installation that lacks the documented Authoring call.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(),
        required_actions=(
            :verify_loaded_package,
            :detect_path_or_version_mismatch,
            :stop_on_missing_documented_api,
            :report_stale_documentation,
        ),
        forbidden_actions=(:silently_use_historical_syntax, :edit_wrong_checkout),
    ),
    (
        id=:existing_process_model,
        title="Minimal model for an existing process",
        workspace_fixture="assets/minimal-model.jl",
        oracle=:existing_process_model,
        oracle_level=:executable_model,
        prompt="Implement a minimal new formulation for an existing process, with complete contracts, a direct kernel test, and one compiled object scenario.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/scenario-coupling.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :inspect_available_processes,
            :reuse_existing_process,
            :test_kernel_directly,
            :validate_model,
            :validate_scenario,
        ),
        forbidden_actions=(:redeclare_dependency_process, :invent_scientific_metadata),
    ),
    (
        id=:drop_in_alternative,
        title="Strictly interchangeable process alternative",
        workspace_fixture="assets/alternative-model.jl",
        oracle=:drop_in_alternative,
        oracle_level=:executable_model,
        prompt="Add a second scientific hypothesis with the same complete interface and establish whether it is a strict drop-in replacement.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/diagnostics.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :reuse_existing_process,
            :compare_models,
            :confirm_direct_override,
            :test_both_kernels,
        ),
        forbidden_actions=(:assume_same_process_is_drop_in, :invent_scientific_metadata),
    ),
    (
        id=:same_process_binding_changes,
        title="Same process with a different interface",
        workspace_fixture="assets/alternative-model.jl",
        oracle=:same_process_binding_changes,
        oracle_level=:executable_model,
        prompt="Implement a same-process alternative that needs an additional input and identify every binding or scenario policy that must change.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/diagnostics.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :reuse_existing_process,
            :compare_models,
            :report_binding_changes,
            :report_reconfiguration,
        ),
        forbidden_actions=(:add_unused_ports_for_compatibility, :hide_required_default),
    ),
    (
        id=:many_subtree_coupling,
        title="Aggregate descendant leaves on one plant",
        workspace_fixture="assets/coupling-patterns.jl",
        oracle=:many_subtree_coupling,
        oracle_level=:executable_model,
        prompt="Couple all descendant leaf outputs into their plant with explicit Many and Subtree selectors, then prove the resolved carriers and bindings.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=("references/scenario-coupling.md",),
        required_actions=(
            :verify_loaded_package,
            :use_many_subtree,
            :validate_scenario,
            :explain_bindings,
            :inspect_public_input_carrier,
        ),
        forbidden_actions=(:copy_reference_carriers, :inspect_compiler_fields),
    ),
    (
        id=:contract_adapter,
        title="Explicit adapter for incompatible physical contracts",
        workspace_fixture="assets/adapter-model.jl",
        oracle=:contract_adapter,
        oracle_level=:executable_model,
        prompt="Show that two physical contracts are incompatible, introduce a named conversion model, and validate the corrected cross-object scenario.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/scenario-coupling.md",
            "references/diagnostics.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :detect_contract_mismatch,
            :implement_named_adapter,
            :test_adapter_directly,
            :validate_scenario,
        ),
        forbidden_actions=(:remove_contract_to_compile, :hide_conversion_factor),
    ),
    (
        id=:missing_environment_input,
        title="Diagnose a missing environmental source",
        workspace_fixture="evaluations/oracles.jl",
        oracle=:missing_environment_input,
        oracle_level=:executable_model,
        prompt="Diagnose why a model-facing environmental input cannot initialize and report the public diagnostic evidence before proposing a source mapping.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/scenario-coupling.md",
            "references/diagnostics.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :validate_scenario,
            :explain_initialization,
            :explain_environment_bindings,
            :report_missing_environment_source,
        ),
        forbidden_actions=(:invent_environment_default, :inspect_compiler_fields),
    ),
    (
        id=:hard_call_publication,
        title="Parent-owned hard call and accepted publication",
        workspace_fixture="assets/runtime-patterns.jl",
        oracle=:hard_call_publication,
        oracle_level=:executable_model,
        prompt="Implement a parent-owned trial call and one accepted call, then prove that only the accepted callee state was published.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=("references/scenario-coupling.md",),
        required_actions=(
            :verify_loaded_package,
            :declare_hard_call,
            :run_trial_without_publication,
            :publish_accepted_call,
            :inspect_retained_stream,
        ),
        forbidden_actions=(:publish_every_trial, :schedule_manual_target_as_root),
    ),
    (
        id=:dynamic_organ_initializer,
        title="Dynamic organ creation with initializer",
        workspace_fixture="assets/lifecycle-output.jl",
        oracle=:dynamic_organ_initializer,
        oracle_level=:executable_model,
        prompt="Add one runtime organ through the owning lifecycle API, run its one-shot initializer, and verify target refresh and non-duplication.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=("references/dynamic-models.md",),
        required_actions=(
            :verify_loaded_package,
            :choose_add_organ_or_register_object,
            :declare_initializer,
            :run_initializer_once,
            :explain_post_lifecycle_applications,
        ),
        forbidden_actions=(:mutate_registry_internals, :double_run_initializer),
    ),
    (
        id=:generic_numeric_types,
        title="Float32 and enriched numeric behavior",
        workspace_fixture="assets/minimal-model.jl",
        oracle=:generic_numeric_types,
        oracle_level=:executable_model,
        prompt="Implement the model without forcing Float64 and test the same kernel with Float32 and one enriched numeric type supported by the fixture.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=("references/model-authoring.md",),
        required_actions=(
            :verify_loaded_package,
            :preserve_generic_parameters,
            :test_float32,
            :test_enriched_numeric_type,
            :report_numeric_limits,
        ),
        forbidden_actions=(:force_float64, :strip_numeric_type),
    ),
    (
        id=:two_process_package_layout,
        title="Small package organized around two processes",
        workspace_fixture="evaluations/fixtures/two-process-package/Project.toml",
        oracle=:two_process_package_layout,
        oracle_level=:executable_model,
        prompt="Organize a small package with two processes, concrete model files, direct and coupling tests, one scenario builder, and process-level scientific documentation pages.",
        required_skills=(:kaimon_julia, :plantsimengine),
        forbidden_skills=(),
        required_references=(
            "references/model-authoring.md",
            "references/scenario-coupling.md",
            "references/repository-layout.md",
        ),
        required_actions=(
            :verify_loaded_package,
            :organize_by_process,
            :separate_direct_and_coupling_tests,
            :build_small_composition,
            :document_scientific_status,
        ),
        forbidden_actions=(:create_empty_architecture_layers, :publish_incomplete_model),
    ),
)
