"""
    compile_model_source(model::CompositeModel;
                         function_name=:compiled_model!,
                         constants=PlantMeteo.Constants())
    compile_model_source(simulation::Simulation;
                         function_name=:compiled_model!)

Generate an executable Julia script that spells out the resolved application
order of a [`CompositeModel`](@ref), includes the source body of every model
kernel, documents resolved inputs and manual calls, and executes those generated
kernels through the normal PlantSimEngine state, environment, output, and
lifecycle machinery.

The generated script defines two methods named by `function_name`: one starts a
fresh simulation from a `CompositeModel`, and one advances an existing
`Simulation`. The default output is intentionally optimized for reading and
review rather than for replacing PlantSimEngine's normal optimized executor.
"""
function compile_model_source(
    model::CompositeModel;
    function_name::Symbol=:compiled_model!,
    constants=PlantMeteo.Constants(),
)
    simulation = run!(model; steps=0, constants=constants, outputs=:none)
    return compile_model_source(simulation; function_name=function_name)
end

function compile_model_source(
    simulation::Simulation;
    function_name::Symbol=:compiled_model!,
)
    _validate_source_function_name(function_name)
    compiled = simulation.compiled
    signature = _compiled_source_scenario_signature(compiled)
    source_id = _compiled_source_id(signature)

    generated_kernels = _compiled_source_kernels(compiled, source_id)
    imports = _compiled_source_imports(generated_kernels)
    kernel_source = join(
        (_compiled_source_kernel_definition(kernel) for kernel in generated_kernels),
        "\n",
    )
    application_source = join(
        (
            _compiled_source_application_block(simulation, entry, source_id)
            for entry in compiled.scenario_plan.application_schedule.entries
        ),
        "\n",
    )

    return string(
        "# This file was generated by PlantSimEngine.compile_model_source.\n",
        "#\n",
        "# It is an executable explanation of a resolved CompositeModel. The\n",
        "# application sections below show execution order, target selection,\n",
        "# input provenance, and manual model calls.\n",
        "#\n",
        "# Source id: ", source_id, "\n",
        "# Application order: ",
        repr(Tuple(entry.application_id for entry in compiled.scenario_plan.application_schedule.entries)),
        "\n\n",
        imports,
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# Generated scientific model kernels\n",
        "# -----------------------------------------------------------------------------\n\n",
        kernel_source,
        "\n",
        "# -----------------------------------------------------------------------------\n",
        "# Explicit resolved model execution\n",
        "# -----------------------------------------------------------------------------\n\n",
        "function ", function_name,
        "(model::PlantSimEngine.CompositeModel; steps::Integer=1, ",
        "constants=PlantMeteo.Constants(), outputs=:none)\n",
        "    simulation = PlantSimEngine.run!(\n",
        "        model; steps=0, constants=constants, outputs=outputs,\n",
        "    )\n",
        "    return ", function_name, "(simulation; steps=steps)\n",
        "end\n\n",
        "function ", function_name,
        "(simulation::PlantSimEngine.Simulation; steps::Integer=1)\n",
        "    steps >= 0 || error(\"`steps` must be non-negative, got \$(steps).\")\n",
        "    PlantSimEngine._compiled_source_assert_compatible(\n",
        "        simulation, ", repr(source_id), ",\n",
        "    )\n",
        "    first_step = simulation.current_step + 1\n",
        "    final_step = simulation.current_step + steps\n",
        "    for timestep in first_step:final_step\n",
        "        due_applications = PlantSimEngine._compiled_source_prepare_step!(\n",
        "            simulation, timestep,\n",
        "        )\n",
        "        completed_applications = Set{Symbol}()\n\n",
        application_source,
        "        PlantSimEngine._compiled_source_finish_step!(simulation, timestep)\n",
        "    end\n",
        "    PlantSimEngine._compiled_source_finalize!(simulation)\n",
        "    return simulation\n",
        "end\n",
    )
end

"""
    write_compiled_model(path, model; kwargs...)

Write [`compile_model_source`](@ref) output to `path` and return `path`.
"""
function write_compiled_model(path::AbstractString, model; kwargs...)
    open(path, "w") do io
        write(io, compile_model_source(model; kwargs...))
    end
    return path
end

struct _CompiledReadableKernel
    source_id::Symbol
    application_id::Symbol
    process::Symbol
    model::Any
    helper_name::Symbol
    method::Method
    source_module::Module
    body::Expr
    input_plans::Any
    call_plans::Any
end

function _validate_source_function_name(function_name::Symbol)
    Base.isidentifier(String(function_name)) || error(
        "Generated model function name `$(function_name)` is not a valid Julia identifier.",
    )
    return function_name
end

function _compiled_source_scenario_signature(compiled::CompiledCompositeModel)
    application_rows = Tuple(
        (
            id=application.id,
            process=application.process,
            models=Tuple(sort!(unique!(
                [_compiled_source_concrete_type_name(model) for model in _compiled_source_application_models(application)],
            ))),
            selector=repr(application.applies_to),
            timestep=repr(application.timestep),
            output_routing=repr(output_routing(application.spec)),
            updates=repr(updates(application.spec)),
        )
        for application in compiled.applications
    )
    input_rows = Tuple(
        (
            application=plan.application_id,
            input=plan.input,
            source_var=plan.source_var,
            origin=plan.origin,
            process=plan.process,
            source_application=plan.application,
            multiplicity=plan.multiplicity,
            previous_timestep=plan.breaks_same_step_cycle,
            selector=repr(plan.selector),
            window=repr(plan.window),
        )
        for plan in compiled.scenario_plan.input_plans
    )
    call_rows = Tuple(
        (
            application=plan.application_id,
            call=plan.call,
            origin=plan.origin,
            process=plan.process,
            target_application=plan.application,
            multiplicity=plan.multiplicity,
            selector=repr(plan.selector),
        )
        for plan in compiled.scenario_plan.call_plans
    )
    schedule_rows = Tuple(
        (
            application=entry.application_id,
            dt=entry.dt,
            phase=entry.phase,
            kind=entry.kind,
        )
        for entry in compiled.scenario_plan.application_schedule.entries
    )
    return (
        applications=application_rows,
        inputs=input_rows,
        calls=call_rows,
        application_order=compiled.scenario_plan.application_order,
        manual_applications=compiled.scenario_plan.manual_application_ids,
        schedule=schedule_rows,
    )
end

function _compiled_source_id(signature)
    value = UInt64(0xcbf29ce484222325)
    for byte in codeunits(repr(signature))
        value = (value ⊻ UInt64(byte)) * UInt64(0x00000100000001b3)
    end
    return Symbol("pse_source_", string(value; base=16, pad=16))
end

function _compiled_source_application_models(application::CompiledModelApplication)
    models = Any[_application_default_model(application)]
    if !isnothing(application.model_overrides)
        for object_id in sort!(collect(keys(application.model_overrides)); by=id -> string(id.value))
            push!(models, application.model_overrides[object_id])
        end
    end
    unique_models = Any[]
    dispatch_names = Set{String}()
    for model in models
        dispatch_name = _compiled_source_concrete_type_name(model)
        dispatch_name in dispatch_names && continue
        push!(dispatch_names, dispatch_name)
        push!(unique_models, model)
    end
    return unique_models
end

function _compiled_source_kernels(compiled::CompiledCompositeModel, source_id::Symbol)
    kernels = _CompiledReadableKernel[]
    for application in compiled.applications
        for (model_index, model) in enumerate(_compiled_source_application_models(application))
            method = _compiled_source_run_method(model)
            source_expression = _compiled_source_method_expression(method)
            parameters = _compiled_source_method_parameters(source_expression)
            length(parameters) == 5 || error(
                "Cannot generate readable source for `$(typeof(model))`: `$(method)` has ",
                "$(length(parameters)) runtime arguments; the CompositeModel contract requires five.",
            )
            bindings = Dict{Symbol,Any}()
            canonical = (:model, :status, :environment, :constants, :context)
            for (parameter, replacement) in zip(parameters, canonical)
                name = first(parameter)
                isnothing(name) || (bindings[name] = replacement)
            end
            body = _compiled_source_method_body(method, source_expression)
            body = _compiled_source_substitute(body, bindings)
            body = _compiled_source_rewrite_manual_calls(body, source_id)
            _compiled_source_assert_no_unrewritten_manual_calls(body, method)
            helper_name = Symbol(
                "__",
                source_id,
                "_",
                _compiled_source_identifier(application.id),
                "_",
                model_index,
                "!",
            )
            push!(
                kernels,
                _CompiledReadableKernel(
                    source_id,
                    application.id,
                    application.process,
                    model,
                    helper_name,
                    method,
                    method.module,
                    body,
                    compiled.scenario_plan.input_plans_by_application[application.id],
                    compiled.scenario_plan.call_plans_by_application[application.id],
                ),
            )
        end
    end
    return kernels
end

function _compiled_source_run_method(model)
    model_type = typeof(model)
    return try
        which(run!, Tuple{model_type,Any,Any,Any,Any})
    catch err
        error(
            "No unambiguous five-argument `run!` method was found for model type ",
            "`$(model_type)`. Julia dispatch reported: $(sprint(showerror, err))",
        )
    end
end

function _compiled_source_method_expression(method::Method)
    file = String(method.file)
    isfile(file) || error(
        "Cannot generate readable source for `$(method)`: source file `$(file)` is unavailable.",
    )
    lines = readlines(file)
    method.line <= length(lines) || error(
        "Cannot generate readable source for `$(method)`: invalid source line $(method.line).",
    )
    buffer = IOBuffer()
    last_error = nothing
    for line_index in method.line:length(lines)
        println(buffer, lines[line_index])
        source = String(take!(copy(buffer)))
        try
            expression = Meta.parse(source)
            function_expression = _compiled_source_unwrap_function_expression(expression)
            isnothing(function_expression) || return function_expression
        catch err
            last_error = err
        end
    end
    error(
        "Cannot parse source for `$(method)` from $(file):$(method.line). ",
        "Last parser error: $(last_error)",
    )
end

function _compiled_source_unwrap_function_expression(expression)
    if Meta.isexpr(expression, :function) || Meta.isexpr(expression, :(=))
        return expression
    elseif Meta.isexpr(expression, :macrocall)
        for argument in expression.args
            unwrapped = _compiled_source_unwrap_function_expression(argument)
            isnothing(unwrapped) || return unwrapped
        end
    end
    return nothing
end

function _compiled_source_method_body(method::Method, expression::Expr)
    body = if Meta.isexpr(expression, :function) || Meta.isexpr(expression, :(=))
        expression.args[2]
    else
        error("Unsupported source expression for `$(method)`.")
    end
    return _compiled_source_clean_expression(body)
end

function _compiled_source_clean_expression(expression)
    expression isa LineNumberNode && return nothing
    expression isa Expr || return expression
    if expression.head === :return &&
       (isempty(expression.args) ||
        (length(expression.args) == 1 && only(expression.args) === nothing))
        return Expr(:return, :nothing)
    end
    cleaned = Any[]
    for argument in expression.args
        if expression.head === :macrocall && argument isa LineNumberNode
            push!(cleaned, argument)
            continue
        end
        value = _compiled_source_clean_expression(argument)
        isnothing(value) || push!(cleaned, value)
    end
    return Expr(expression.head, cleaned...)
end

function _compiled_source_function_signature(expression::Expr)
    if Meta.isexpr(expression, :function) || Meta.isexpr(expression, :(=))
        return expression.args[1]
    end
    error("Unsupported function source expression.")
end

function _compiled_source_call_arguments(signature)
    if Meta.isexpr(signature, :call)
        return signature.args[2:end]
    elseif Meta.isexpr(signature, :where)
        return _compiled_source_call_arguments(signature.args[1])
    end
    return Any[]
end

function _compiled_source_method_parameters(expression::Expr)
    arguments = _compiled_source_call_arguments(
        _compiled_source_function_signature(expression),
    )
    return Pair{Union{Nothing,Symbol},Any}[
        _compiled_source_argument_name(argument) =>
        _compiled_source_argument_default(argument)
        for argument in arguments
        if !Meta.isexpr(argument, :parameters)
    ]
end

function _compiled_source_argument_default(argument)
    if Meta.isexpr(argument, :(=)) || Meta.isexpr(argument, :kw)
        return argument.args[2]
    end
    return nothing
end

function _compiled_source_argument_name(argument)
    if Meta.isexpr(argument, :(=)) || Meta.isexpr(argument, :kw)
        return _compiled_source_argument_name(argument.args[1])
    elseif argument isa Symbol
        return argument
    elseif Meta.isexpr(argument, :(::))
        return length(argument.args) == 2 && argument.args[1] isa Symbol ?
               argument.args[1] : nothing
    end
    return nothing
end

function _compiled_source_substitute(expression, bindings::Dict{Symbol,Any})
    if expression isa Symbol
        return get(bindings, expression, expression)
    elseif expression isa QuoteNode || expression isa LineNumberNode
        return expression
    elseif expression isa Expr
        return Expr(
            expression.head,
            (_compiled_source_substitute(argument, bindings) for argument in expression.args)...,
        )
    end
    return expression
end

function _compiled_source_rewrite_manual_calls(expression, source_id::Symbol)
    expression isa Expr || return expression
    if Meta.isexpr(expression, :call) &&
       _compiled_source_is_run_call_function(expression.args[1])
        rewritten_arguments = Any[
            _compiled_source_rewrite_manual_calls(argument, source_id)
            for argument in expression.args[2:end]
        ]
        source_value = Expr(:call, :Val, QuoteNode(source_id))
        function_expression = Expr(
            :.,
            :PlantSimEngine,
            QuoteNode(:_compiled_source_run_call!),
        )
        if !isempty(rewritten_arguments) && Meta.isexpr(first(rewritten_arguments), :parameters)
            return Expr(
                :call,
                function_expression,
                first(rewritten_arguments),
                source_value,
                Base.tail(Tuple(rewritten_arguments))...,
            )
        end
        return Expr(:call, function_expression, source_value, rewritten_arguments...)
    end
    return Expr(
        expression.head,
        (_compiled_source_rewrite_manual_calls(argument, source_id) for argument in expression.args)...,
    )
end

_compiled_source_is_run_call_function(function_expression) =
    function_expression === :run_call!

function _compiled_source_is_run_call_function(function_expression::Expr)
    return Meta.isexpr(function_expression, :.) &&
           length(function_expression.args) == 2 &&
           function_expression.args[1] in (:PlantSimEngine, Symbol(@__MODULE__)) &&
           function_expression.args[2] == QuoteNode(:run_call!)
end

function _compiled_source_assert_no_unrewritten_manual_calls(expression, method::Method)
    _compiled_source_contains_run_call_reference(expression) && error(
        "Cannot generate readable source for `$(method)`: a `run_call!` alias or ",
        "unsupported call shape remained after rewriting. Call `run_call!` directly ",
        "or qualify it as `PlantSimEngine.run_call!`.",
    )
    return nothing
end

function _compiled_source_contains_run_call_reference(expression)
    expression isa QuoteNode && return false
    expression === :run_call! && return true
    expression isa Expr || return false
    _compiled_source_is_run_call_function(expression) && return true
    return any(_compiled_source_contains_run_call_reference, expression.args)
end

function _compiled_source_identifier(value)
    text = replace(string(value), r"[^A-Za-z0-9_]" => "_")
    isempty(text) && return "application"
    isdigit(first(text)) && (text = "application_" * text)
    return text
end

function _compiled_source_module_path(source_module::Module)
    source_module === Main && return "Main"
    names = Symbol[]
    current = source_module
    while current !== Main
        pushfirst!(names, nameof(current))
        parent = parentmodule(current)
        parent === current && break
        current = parent
    end
    return join(string.(names), ".")
end

function _compiled_source_root_module(source_module::Module)
    current = source_module
    parent = parentmodule(current)
    while parent !== Main && parent !== current
        current = parent
        parent = parentmodule(current)
    end
    return current
end

function _compiled_source_dispatch_type_name(model)
    wrapper = Base.typename(typeof(model)).wrapper
    source_module = parentmodule(wrapper)
    module_path = _compiled_source_module_path(source_module)
    return string(module_path, ".", nameof(wrapper))
end

function _compiled_source_concrete_type_name(model)
    concrete_type = typeof(model)
    wrapper_name = _compiled_source_dispatch_type_name(model)
    isempty(concrete_type.parameters) && return wrapper_name
    parameters = join(repr.(concrete_type.parameters), ", ")
    return string(wrapper_name, "{", parameters, "}")
end

function _compiled_source_imports(kernels)
    imports = String["import PlantSimEngine\n", "import PlantMeteo\n"]
    roots = Set{Module}()
    for kernel in kernels
        root = _compiled_source_root_module(kernel.source_module)
        root in (Main, PlantSimEngine, PlantMeteo, Base, Core) && continue
        push!(roots, root)
    end
    for root in sort!(collect(roots); by=string)
        push!(imports, "import $(_compiled_source_module_path(root))\n")
    end
    return join(imports)
end

function _compiled_source_render(expression)
    io = IOBuffer()
    Base.show_unquoted(io, expression, 0, 0)
    return String(take!(io))
end

function _compiled_source_indent(text::AbstractString, spaces::Int)
    prefix = repeat(" ", spaces)
    return join((isempty(line) ? line : prefix * line for line in split(text, '\n')), "\n")
end

function _compiled_source_kernel_definition(kernel::_CompiledReadableKernel)
    helper_signature = Expr(
        :call,
        kernel.helper_name,
        :model,
        :status,
        :environment,
        :constants,
        :context,
    )
    helper_expression = Expr(:function, helper_signature, kernel.body)
    module_path = _compiled_source_module_path(kernel.source_module)
    dispatch_type = _compiled_source_concrete_type_name(kernel.model)
    inputs = join(string.(keys(inputs_(kernel.model))), ", ")
    outputs = join(string.(keys(outputs_(kernel.model))), ", ")
    isempty(inputs) && (inputs = "none")
    isempty(outputs) && (outputs = "none")
    resolved_inputs = isempty(kernel.input_plans) ?
                      "# Resolved inputs: none\n" :
                      join(
        ("# " * _compiled_source_input_description(plan) * "\n" for plan in kernel.input_plans),
    )
    resolved_calls = isempty(kernel.call_plans) ?
                     "# Manual calls: none\n" :
                     join(
        ("# " * _compiled_source_call_description(plan) * "\n" for plan in kernel.call_plans),
    )
    return string(
        "# Application :", kernel.application_id,
        " | process :", kernel.process,
        " | model ", typeof(kernel.model), "\n",
        "# Original method: ", kernel.method, "\n",
        "# Source: ", String(kernel.method.file), ":", kernel.method.line, "\n",
        "# Inputs: ", inputs, " | outputs: ", outputs, "\n",
        resolved_inputs,
        resolved_calls,
        "Core.eval(", module_path, ", quote\n",
        _compiled_source_indent(_compiled_source_render(helper_expression), 4), "\n",
        "end)\n\n",
        "function PlantSimEngine._compiled_source_kernel!(\n",
        "    ::Val{", repr(kernel.source_id), "},\n",
        "    ::Val{", repr(kernel.application_id), "},\n",
        "    model::", dispatch_type, ",\n",
        "    status, environment, constants, context,\n",
        ")\n",
        "    return ", module_path, ".", kernel.helper_name,
        "(model, status, environment, constants, context)\n",
        "end\n",
    )
end

function _compiled_source_object_summary(model::CompositeModel, object_ids)
    isempty(object_ids) && return "none"
    labels = String[]
    for object_id in object_ids
        object = _model_object(model, object_id)
        push!(
            labels,
            string(
                object_id.value,
                " (scale=", object.scale,
                ", kind=", object.kind,
                ")",
            ),
        )
    end
    return join(labels, ", ")
end

function _compiled_source_value_description(value)
    value isa PreviousTimeStep && return "PreviousTimeStep($(repr(value.variable)))"
    return repr(value)
end

function _compiled_source_selector_description(selector::AbstractObjectMultiplicity)
    selector_criteria = criteria(selector)
    arguments = String[
        _compiled_source_value_description(value)
        for value in selector_criteria.selectors
    ]
    for key in keys(selector_criteria)
        key === :selectors && continue
        push!(
            arguments,
            "$(key)=$(_compiled_source_value_description(getproperty(selector_criteria, key)))",
        )
    end
    selector_name = nameof(Base.typename(typeof(selector)).wrapper)
    return string(selector_name, "(", join(arguments, ", "), ")")
end

function _compiled_source_environment_description(spec)
    config = environment_config(spec)
    isnothing(config) && return "scenario default"
    values = config.config
    arguments = join(
        ("$(key)=$(repr(getproperty(values, key)))" for key in keys(values)),
        ", ",
    )
    return string("Environment(", arguments, ")")
end

function _compiled_source_output_routing_description(spec)
    routing = output_routing(spec)
    isempty(routing) && return "canonical (all declared outputs)"
    return join(
        ("$(key)=>$(repr(getproperty(routing, key)))" for key in keys(routing)),
        ", ",
    )
end

function _compiled_source_input_description(plan)
    source = isnothing(plan.application) ?
             (isnothing(plan.process) ? "inferred producer" : "process :$(plan.process)") :
             "application :$(plan.application)"
    lag = plan.breaks_same_step_cycle ? " (previous timestep)" : ""
    return "input :$(plan.input) <- $(source).$(plan.source_var) via $(plan.multiplicity)$(lag); " *
           "selector=$(_compiled_source_selector_description(plan.selector)); " *
           "window=$(_compiled_source_value_description(plan.window))"
end

function _compiled_source_call_description(plan)
    target = isnothing(plan.application) ?
             (isnothing(plan.process) ? "resolved application" : "process :$(plan.process)") :
             "application :$(plan.application)"
    return "manual call :$(plan.call) -> $(target) via $(plan.multiplicity); " *
           "selector=$(_compiled_source_selector_description(plan.selector))"
end

function _compiled_source_application_comments(
    simulation::Simulation,
    application::CompiledModelApplication,
    entry::CompiledApplicationScheduleEntry,
)
    lines = String[
        "Application :$(application.id)",
        "process: :$(application.process)",
        "cadence: dt=$(entry.dt), phase=$(entry.phase), schedule=$(entry.kind)",
        "target selector: $(_compiled_source_selector_description(application.applies_to))",
        "current targets: $(_compiled_source_object_summary(simulation.model, application.target_ids))",
        "environment: $(_compiled_source_environment_description(application.spec))",
        "output routing: $(_compiled_source_output_routing_description(application.spec))",
    ]
    input_plans = simulation.compiled.scenario_plan.input_plans_by_application[application.id]
    if isempty(input_plans)
        push!(lines, "inputs: none")
    else
        for plan in input_plans
            push!(lines, _compiled_source_input_description(plan))
        end
    end
    call_plans = simulation.compiled.scenario_plan.call_plans_by_application[application.id]
    if isempty(call_plans)
        push!(lines, "manual calls: none")
    else
        for plan in call_plans
            push!(lines, _compiled_source_call_description(plan))
        end
    end
    return lines
end

function _compiled_source_application_block(
    simulation::Simulation,
    entry::CompiledApplicationScheduleEntry,
    source_id::Symbol,
)
    application = simulation.compiled.applications_by_id[entry.application_id]
    comments = join(("        # " * line * "\n" for line in _compiled_source_application_comments(
        simulation,
        application,
        entry,
    )))
    application_id = repr(application.id)
    return string(
        comments,
        "        if ", application_id, " in due_applications\n",
        "            application = simulation.compiled.applications_by_id[", application_id, "]\n",
        "            # Resolve the objects selected by this application at the current\n",
        "            # lifecycle revision, then run the visible scientific kernel once\n",
        "            # for each object.\n",
        "            for resolved_target in PlantSimEngine._compiled_source_targets(\n",
        "                simulation, ", application_id, ", timestep,\n",
        "            )\n",
        "                target = resolved_target.target\n",
        "                status, environment, context =\n",
        "                    PlantSimEngine._compiled_source_prepare_target!(\n",
        "                        simulation, application, target, timestep,\n",
        "                        resolved_target.shared_environment,\n",
        "                    )\n",
        "                PlantSimEngine._compiled_source_kernel!(\n",
        "                    Val(", repr(source_id), "), Val(", application_id, "),\n",
        "                    target.model, status, environment,\n",
        "                    simulation.constants, context,\n",
        "                )\n",
        "                PlantSimEngine._compiled_source_publish_target!(\n",
        "                    target, timestep, resolved_target.publish_outputs,\n",
        "                )\n",
        "            end\n",
        "        end\n",
        "        push!(completed_applications, ", application_id, ")\n",
        "        PlantSimEngine._compiled_source_refresh_after_application!(\n",
        "            simulation, completed_applications,\n",
        "        )\n\n",
    )
end

function _compiled_source_assert_compatible(simulation::Simulation, expected_source_id::Symbol)
    current_source_id = _compiled_source_id(
        _compiled_source_scenario_signature(simulation.compiled),
    )
    current_source_id == expected_source_id || error(
        "Generated model source is incompatible with this CompositeModel. ",
        "Regenerate the script after changing applications, model types, inputs, ",
        "manual calls, cadence, or output routing.",
    )
    return simulation
end

function _compiled_source_prepare_step!(simulation::Simulation, step::Integer)
    step == simulation.current_step + 1 || error(
        "Generated model execution expected step $(simulation.current_step + 1), got $(step).",
    )
    lifecycle = _pending_output_request_lifecycle_delta(simulation.model)
    _refresh_simulation_runtime!(simulation)
    _refresh_output_request_targets!(simulation, lifecycle)
    empty!(simulation.environment_bindings.sample_cache)
    schedule_plan = simulation.compiled.scenario_plan.application_schedule
    due_indices = _due_application_schedule_entries!(
        simulation.execution_plan.schedule,
        schedule_plan,
        Int(step),
    )
    return Set{Symbol}(
        schedule_plan.entries[index].application_id for index in due_indices
    )
end

function _compiled_source_application_group(simulation::Simulation, application_id::Symbol)
    application = simulation.compiled.applications_by_id[application_id]
    return simulation.execution_plan.groups_by_application_slot[application.slot]
end

function _compiled_source_targets(
    simulation::Simulation,
    application_id::Symbol,
    time::Real,
)
    group = _compiled_source_application_group(simulation, application_id)
    isnothing(group) && return NamedTuple[]
    targets = NamedTuple[]
    for batch in group.batches
        shared_environment, publish_outputs =
            _compiled_source_prepare_batch(simulation, batch, time)
        for target in batch.targets
            push!(
                targets,
                (;
                    object_id=target.object_id,
                    target,
                    shared_environment,
                    publish_outputs,
                ),
            )
        end
    end
    return targets
end

function _compiled_source_prepare_batch(
    simulation::Simulation,
    batch::CompiledExecutionBatch,
    time::Real,
)
    shared_environment = _model_execution_batch_environment(
        batch.environment_provider,
        simulation.environment_bindings,
        batch.application,
        time,
    )
    return shared_environment, batch.output_publication.enabled
end

function _compiled_source_prepare_target!(
    simulation::Simulation,
    application::CompiledModelApplication,
    target::CompiledExecutionTarget,
    time::Real,
    shared_environment,
)
    status = isempty(target.input_bindings) ?
             target.status :
             _materialize_model_inputs!(
        target.status,
        target.input_bindings,
        simulation.compiled,
        application,
        simulation.temporal_streams,
        time,
    )
    environment = shared_environment isa UnspecifiedModelEnvironment ?
                  _model_environment_for_binding(
        simulation.environment_bindings,
        application,
        target.environment_binding,
        time,
    ) : shared_environment
    context = _prepare_model_execution_context!(
        target.context,
        simulation.compiled,
        simulation.environment_bindings,
        application,
        target.object_id,
        simulation.temporal_streams,
        simulation.output_retention,
        time,
        simulation.constants,
    )
    return status, environment, context
end

function _compiled_source_publish_target!(
    target::CompiledExecutionTarget,
    time::Real,
    publish_outputs::Bool,
)
    publish_outputs || return nothing
    isempty(target.output_bindings) ||
        _model_publish_runtime_outputs!(target.output_bindings, time)
    return nothing
end

function _compiled_source_refresh_after_application!(
    simulation::Simulation,
    completed_applications::Set{Symbol},
)
    _simulation_runtime_dirty(simulation) || return simulation
    lifecycle = _pending_output_request_lifecycle_delta(simulation.model)
    _refresh_simulation_runtime!(simulation)
    _refresh_output_request_targets!(
        simulation,
        lifecycle,
        completed_applications,
    )
    empty!(simulation.environment_bindings.sample_cache)
    return simulation
end

function _compiled_source_finish_step!(simulation::Simulation, step::Integer)
    simulation.current_step = Int(step)
    return simulation
end

function _compiled_source_finalize!(simulation::Simulation)
    lifecycle = _pending_output_request_lifecycle_delta(simulation.model)
    _refresh_simulation_runtime!(simulation)
    _refresh_output_request_targets!(simulation, lifecycle)
    return simulation
end

function _compiled_source_kernel! end

function _compiled_source_run_call_target!(
    source_id::Val,
    targets::CallTargets,
    application::CompiledModelApplication,
    target::CompiledExecutionTarget,
    publish::Bool,
    sampled_environment,
    environment,
)
    status = _materialize_model_inputs!(
        target.status,
        target.input_bindings,
        targets.compiled,
        application,
        targets.temporal_streams,
        targets.time,
    )
    environment_value = sampled_environment isa UnspecifiedModelEnvironment ?
                        _model_environment_for_binding(
        targets.environment_bindings,
        application,
        target.environment_binding,
        targets.time,
        environment,
    ) : sampled_environment
    publication_allowed = publish && targets.publication_allowed
    context = _prepare_model_execution_context!(
        target.context,
        targets.compiled,
        targets.environment_bindings,
        application,
        target.object_id,
        targets.temporal_streams,
        targets.output_retention,
        targets.time,
        targets.constants,
        publication_allowed,
        environment,
    )
    _compiled_source_kernel!(
        source_id,
        Val(application.id),
        target.model,
        status,
        environment_value,
        targets.constants,
        context,
    )
    if publication_allowed
        isempty(target.output_bindings) ||
            _model_publish_runtime_outputs!(target.output_bindings, targets.time)
    end
    return nothing
end

function _compiled_source_run_call!(
    source_id::Val,
    context::RunContext,
    name::Symbol;
    environment=_NO_ENVIRONMENT_OVERRIDE,
    sampled_environment=_UNSPECIFIED_SCENE_ENVIRONMENT,
    publish::Bool=false,
    objects=nothing,
)
    if !(environment isa NoEnvironmentOverride) &&
       !(sampled_environment isa UnspecifiedModelEnvironment)
        throw(
            ArgumentError(
                "`environment` and `sampled_environment` are mutually exclusive hard-call overrides.",
            ),
        )
    end
    targets = isnothing(objects) ?
              call_targets(context, name) :
              call_targets(context, name; objects=objects)
    selected_environment = environment isa NoEnvironmentOverride ?
                           context.environment :
                           environment
    for batch in targets.execution_batches
        for target in batch.targets
            _compiled_source_run_call_target!(
                source_id,
                targets,
                batch.application,
                target,
                publish,
                sampled_environment,
                selected_environment,
            )
        end
    end
    return targets
end

function _compiled_source_run_call!(
    source_id::Val,
    target::CallTarget;
    publish::Bool=false,
    sampled_environment=_UNSPECIFIED_SCENE_ENVIRONMENT,
)
    status = _materialize_model_inputs!(
        target.status,
        target.temporal_inputs,
        target.compiled,
        target.application,
        target.temporal_streams,
        target.time,
    )
    environment_value = sampled_environment isa UnspecifiedModelEnvironment ?
                        _model_environment_for_binding(
        target.environment_bindings,
        target.application,
        target.environment_binding,
        target.time,
        target.environment,
    ) : sampled_environment
    publication_allowed = publish && target.publication_allowed
    _prepare_runtime_call_targets!(
        target.calls,
        target.compiled,
        target.environment_bindings,
        target.temporal_streams,
        target.output_retention,
        target.time,
        target.constants,
        publication_allowed,
        target.environment,
    )
    context = RunContext(
        target.compiled,
        target.environment_bindings,
        target.application,
        target.object_id,
        target.calls,
        target.temporal_streams,
        target.output_retention,
        target.time,
        target.constants,
        publication_allowed,
        target.environment,
    )
    _compiled_source_kernel!(
        source_id,
        Val(target.application.id),
        target.model,
        status,
        environment_value,
        target.constants,
        context,
    )
    if publication_allowed
        isempty(target.output_bindings) ||
            _model_publish_runtime_outputs!(target.output_bindings, target.time)
    end
    return target
end
