"""
    compile_model(mapping; function_name=:compiled_model!)
    compile_model(model_list; function_name=:compiled_model!)

Generate a Julia script containing one merged model function for a single-scale
model mapping. The generated function keeps `models`, `status`, `meteo`,
`constants`, and `extra` as arguments, so model parameters still come from the
original mapping/model list.

Hard dependency calls to `run!(models.process, ...)` are recursively replaced by
the source body of the called model. Soft dependencies are emitted in dependency
graph order.
"""
function compile_model(mapping::ModelMapping{SingleScale}; function_name::Symbol=:compiled_model!)
    return compile_model(_modellist_from_model_mapping(mapping); function_name=function_name)
end

function compile_model(::ModelMapping{MultiScale}; function_name::Symbol=:compiled_model!)
    error("`compile_model` currently supports single-scale `ModelMapping`s. Build a `GraphSimulation` first if you need MTG-specific execution context.")
end

function compile_model(model_list::ModelList; function_name::Symbol=:compiled_model!)
    dep_graph = dep(model_list)
    length(dep_graph.not_found) > 0 && error("Cannot compile model with missing dependencies: $(dep_graph.not_found)")

    nodes = _topological_soft_nodes(dep_graph)
    ctx = _ModelCompilationContext(model_list.models, Dict{Tuple{Symbol,Symbol,DataType},_CompiledModelSource}(), Set{Module}(), Dict(:Default => 1))
    statements = Any[]
    for node in nodes
        call = _CompiledRunCall(
            :(models.$(node.process)),
            :models,
            :status,
            :meteo,
            :constants,
            :extra
        )
        append!(statements, _inline_model_node(ctx, node, call, Set{Tuple{Symbol,Symbol}}()))
    end

    body = Expr(:block, statements..., :(return nothing))
    fexpr = Expr(
        :function,
        Expr(:call, function_name, :models, :status, :meteo, :constants, :extra),
        body
    )

    return string(
        "# This file was generated by PlantSimEngine.compile_model.\n",
        "# It expects `models` to be the model mapping/list used for compilation.\n\n",
        _compiled_module_imports(ctx.source_modules),
        _sprint_expr(fexpr),
        "\n"
    )
end

function compile_model(sim::GraphSimulation; function_name::Symbol=:compiled_model!)
    is_multirate(sim) && error("`compile_model(::GraphSimulation)` currently supports same-rate MTG simulations only. Multi-rate compilation is not implemented yet.")
    dep_graph = dep(sim)
    length(dep_graph.not_found) > 0 && error("Cannot compile model with missing dependencies: $(dep_graph.not_found)")

    nodes = _topological_soft_nodes(dep_graph)
    ctx = _ModelCompilationContext(get_models(sim), Dict{Tuple{Symbol,Symbol,DataType},_CompiledModelSource}(), Set{Module}(), _initial_status_counts(sim))
    step_statements = Any[]
    for node in nodes
        append!(step_statements, _multiscale_node_loop(ctx, sim, node))
    end

    one_step_body = Expr(:block, step_statements...)
    body = Expr(
        :block,
        :(statuses = PlantSimEngine.status(sim)),
        :(models_by_scale = PlantSimEngine.get_models(sim)),
        :(nsteps = PlantSimEngine.get_nsteps(meteo)),
        Expr(
            :if,
            :(nsteps == 1),
            Expr(
                :block,
                :(meteo_i = meteo),
                one_step_body,
                :(PlantSimEngine.save_results!(sim, 1))
            ),
            Expr(
                :block,
                :(i = 1),
                Expr(
                    :for,
                    :(meteo_i = PlantSimEngine.Tables.rows(meteo)),
                    Expr(
                        :block,
                        one_step_body,
                        :(PlantSimEngine.save_results!(sim, i)),
                        :(i += 1)
                    )
                )
            )
        ),
        Expr(
            :for,
            :((organ, index) = sim.outputs_index),
            :(resize!(PlantSimEngine.outputs(sim)[organ], index - 1))
        ),
        :(return PlantSimEngine.outputs(sim))
    )
    fexpr = Expr(:function, Expr(:call, function_name, :sim, :meteo, :constants), body)

    return string(
        "# This file was generated by PlantSimEngine.compile_model.\n",
        "# It expects `sim` to be the initialized GraphSimulation used for compilation.\n",
        "# Mode: same-rate multiscale MTG; variables are scale-scoped through each Status.\n",
        "# Cross-scale sharing comes from initialized Refs and RefVectors in sim.statuses.\n",
        "# Initial statuses by scale: $(_initial_status_counts(sim)).\n",
        "# Processes by scale: $(_processes_by_scale(sim)).\n\n",
        _compiled_module_imports(ctx.source_modules),
        _sprint_expr(fexpr),
        "\n"
    )
end

"""
    write_compiled_model(path, mapping; function_name=:compiled_model!)

Write the script generated by [`compile_model`](@ref) to `path` and return the
path.
"""
function write_compiled_model(path::AbstractString, mapping; function_name::Symbol=:compiled_model!)
    open(path, "w") do io
        write(io, compile_model(mapping; function_name=function_name))
    end
    return path
end

struct _CompiledModelSource
    method::Method
    expression::Expr
    body::Expr
    parameters::Vector{Pair{Union{Nothing,Symbol},Any}}
end

struct _CompiledRunCall
    model
    models
    status
    meteo
    constants
    extra
end

struct _ModelCompilationContext{M}
    models::M
    source_cache::Dict{Tuple{Symbol,Symbol,DataType},_CompiledModelSource}
    source_modules::Set{Module}
    initial_status_counts::Dict{Symbol,Int}
end

function _topological_soft_nodes(dep_graph::DependencyGraph)
    traversal_order = traverse_dependency_graph(dep_graph, false)
    pending = Set(traversal_order)
    ordered = SoftDependencyNode[]

    while !isempty(pending)
        progressed = false
        for node in traversal_order
            node in pending || continue
            parents = isnothing(node.parent) ? SoftDependencyNode[] : node.parent
            if all(parent -> !(parent in pending), parents)
                push!(ordered, node)
                delete!(pending, node)
                progressed = true
            end
        end
        progressed || error("Cannot compile cyclic dependency graph.")
    end

    return ordered
end

function _inline_model_node(ctx::_ModelCompilationContext, node::AbstractDependencyNode, call::_CompiledRunCall, stack::Set{Tuple{Symbol,Symbol}})
    node_key = (node.scale, node.process)
    node_key in stack && error("Cyclic hard dependency while compiling process `$(node.process)` at scale `$(node.scale)`.")

    source_key = (node.scale, node.process, typeof(node.value))
    source = get!(ctx.source_cache, source_key) do
        _compiled_model_source(ctx, node.value)
    end
    bindings = _argument_bindings(source, call)
    compiled_body = _rewrite_run_body(ctx, source.body, bindings, push!(copy(stack), node_key), node.scale)
    compiled_body = _strip_return_expr(compiled_body)

    statements = Any[
        LineNumberNode(0, Symbol(_model_metadata_comment(ctx, node, source))),
        :(model = $(call.model))
    ]
    append!(statements, _block_statements(compiled_body))

    return Any[Expr(:let, Expr(:block), Expr(:block, statements...))]
end

function _multiscale_node_loop(ctx::_ModelCompilationContext, sim::GraphSimulation, node::SoftDependencyNode)
    call = _CompiledRunCall(
        :((models_by_scale[$(QuoteNode(node.scale))]).$(node.process)),
        :(models_by_scale[$(QuoteNode(node.scale))]),
        :status,
        :meteo_i,
        :constants,
        :sim
    )
    body = _inline_model_node(ctx, node, call, Set{Tuple{Symbol,Symbol}}())
    statements = Any[
        LineNumberNode(0, Symbol("scale loop: $(node.scale) | process: $(node.process) | initial_statuses: $(length(status(sim)[node.scale]))")),
        :(idx = 1),
        Expr(
            :while,
            :(idx <= length(statuses[$(QuoteNode(node.scale))])),
            Expr(
                :block,
                :(status = statuses[$(QuoteNode(node.scale))][idx]),
                body...,
                :(idx += 1)
            )
        )
    ]
    return Any[Expr(:let, Expr(:block), Expr(:block, statements...))]
end

function _compiled_model_source(ctx::_ModelCompilationContext, model)
    method = _run_method_for_model(model)
    push!(ctx.source_modules, method.module)
    fexpr = _method_expr_from_source(method)
    return _CompiledModelSource(method, fexpr, _method_body_from_expr(method, fexpr), _method_parameters(fexpr))
end

function _argument_bindings(source::_CompiledModelSource, call::_CompiledRunCall)
    values = Any[call.model, call.models, call.status, call.meteo, call.constants, call.extra]
    bindings = Dict{Symbol,Any}()
    for (i, parameter) in enumerate(source.parameters)
        name, default = first(parameter), last(parameter)
        isnothing(name) && continue
        if i <= length(values)
            bindings[name] = values[i]
        elseif !isnothing(default)
            bindings[name] = default
        else
            error("Cannot inline `$(source.method)`: missing argument `$name` and no default value was found.")
        end
    end
    return bindings
end

function _model_metadata_comment(ctx::_ModelCompilationContext, node::AbstractDependencyNode, source::_CompiledModelSource)
    initial_statuses = get(ctx.initial_status_counts, node.scale, 0)
    return join(
        (
            "model: $(typeof(node.value))",
            "process: $(node.process)",
            "scale: $(node.scale)",
            "initial_statuses: $initial_statuses",
            "module: $(source.method.module)",
            "source: $(String(source.method.file)):$(source.method.line)",
            "method: $(source.method)"
        ),
        " | "
    )
end

function _compiled_module_imports(modules::Set{Module})
    imports = String[
        "using PlantSimEngine\n",
        "using MultiScaleTreeGraph\n",
        "using PlantMeteo\n",
        "using Statistics\n",
    ]
    for mod in sort!(collect(modules), by=string)
        mod in (PlantSimEngine, Main) && continue
        push!(imports, "using $(_module_path(mod))\n")
    end
    push!(imports, "\n")
    return join(imports)
end

function _module_path(mod::Module)
    names = Symbol[]
    current = mod
    while current !== Main
        pushfirst!(names, nameof(current))
        parent = parentmodule(current)
        parent === current && break
        current = parent
    end
    return join(string.(names), ".")
end

function _initial_status_counts(sim::GraphSimulation)
    return Dict(scale => length(statuses) for (scale, statuses) in status(sim))
end

function _processes_by_scale(sim::GraphSimulation)
    return Dict(scale => collect(keys(models)) for (scale, models) in get_models(sim))
end

function _run_method_for_model(model)
    model_type = typeof(model)
    candidates = Method[]
    for method in methods(run!)
        sig = Base.unwrap_unionall(method.sig)
        sig <: Tuple || continue
        length(sig.parameters) >= 2 || continue
        model_arg = sig.parameters[2]
        model_arg isa Type || continue
        model_type <: model_arg || continue
        push!(candidates, method)
    end

    isempty(candidates) && error("No `run!` method found for model type `$(model_type)`.")
    exact = filter(candidates) do method
        sig = Base.unwrap_unionall(method.sig)
        sig.parameters[2] == model_type
    end
    if !isempty(exact)
        max_arity = maximum(method -> length(Base.unwrap_unionall(method.sig).parameters), exact)
        exact_max = filter(method -> length(Base.unwrap_unionall(method.sig).parameters) == max_arity, exact)
        length(exact_max) == 1 && return only(exact_max)
    end

    non_any = filter(candidates) do method
        sig = Base.unwrap_unionall(method.sig)
        sig.parameters[2] != Any
    end
    if !isempty(non_any)
        max_arity = maximum(method -> length(Base.unwrap_unionall(method.sig).parameters), non_any)
        non_any_max = filter(method -> length(Base.unwrap_unionall(method.sig).parameters) == max_arity, non_any)
        length(non_any_max) == 1 && return only(non_any_max)
    end

    length(candidates) == 1 && return only(candidates)

    error(
        "Several `run!` methods match model type `$(model_type)`. ",
        "`compile_model` needs a single concrete model method."
    )
end

function _method_body_from_expr(method::Method, fexpr::Expr)
    body = if Meta.isexpr(fexpr, :function)
        fexpr.args[2]
    elseif Meta.isexpr(fexpr, :(=))
        fexpr.args[2]
    else
        error("Unsupported method expression for `$method`.")
    end
    return _clean_source_expr(body)
end

function _method_expr_from_source(method::Method)
    file = String(method.file)
    line = method.line
    isfile(file) || error("Cannot find source file for `$method`: $file")
    lines = readlines(file)
    line <= length(lines) || error("Invalid source location for `$method`: $file:$line")

    buffer = IOBuffer()
    last_error = nothing
    for i in line:length(lines)
        println(buffer, lines[i])
        source = String(take!(copy(buffer)))
        try
            expr = Meta.parse(source)
            if Meta.isexpr(expr, :function) || Meta.isexpr(expr, :(=))
                return expr
            end
        catch err
            last_error = err
        end
    end
    error("Failed to parse source for `$method` from $file:$line. Last parser error: $last_error")
end

function _clean_source_expr(expr)
    if expr isa LineNumberNode
        return nothing
    elseif Meta.isexpr(expr, :block)
        return Expr(:block, filter(!isnothing, Any[_clean_source_expr(arg) for arg in expr.args])...)
    elseif expr isa Expr
        return Expr(expr.head, filter(!isnothing, Any[_clean_source_expr(arg) for arg in expr.args])...)
    else
        return expr
    end
end

function _function_signature(expr::Expr)
    if Meta.isexpr(expr, :function)
        return expr.args[1]
    elseif Meta.isexpr(expr, :(=))
        return expr.args[1]
    end
    error("Unsupported function expression.")
end

function _call_arguments(sig)
    if Meta.isexpr(sig, :call)
        return sig.args[2:end]
    elseif Meta.isexpr(sig, :where)
        return _call_arguments(sig.args[1])
    end
    return Any[]
end

function _method_parameters(fexpr::Expr)
    args = _call_arguments(_function_signature(fexpr))
    return Pair{Union{Nothing,Symbol},Any}[_argument_name(arg) => _argument_default(arg) for arg in args]
end

function _argument_default(arg)
    if Meta.isexpr(arg, :(=)) || Meta.isexpr(arg, :kw)
        return arg.args[2]
    end
    return nothing
end

function _argument_name(arg)
    if Meta.isexpr(arg, :(=))
        return _argument_name(arg.args[1])
    end
    return _argument_name_without_default(arg)
end

function _argument_name_without_default(arg)
    arg isa Symbol && return arg
    if Meta.isexpr(arg, :(::))
        return length(arg.args) == 2 && arg.args[1] isa Symbol ? arg.args[1] : nothing
    elseif Meta.isexpr(arg, :kw)
        return _argument_name(arg.args[1])
    end
    return nothing
end

function _rewrite_run_body(ctx::_ModelCompilationContext, expr, bindings::Dict{Symbol,Any}, stack::Set{Tuple{Symbol,Symbol}}, current_scale::Symbol)
    if expr isa Symbol
        return get(bindings, expr, expr)
    elseif expr isa QuoteNode || expr isa LineNumberNode
        return expr
    elseif expr isa Expr
        if Meta.isexpr(expr, :call) && _is_run_function(expr.args[1])
            return _inline_run_call(ctx, expr, bindings, stack, current_scale)
        end
        return Expr(expr.head, (_rewrite_run_body(ctx, arg, bindings, stack, current_scale) for arg in expr.args)...)
    end
    return expr
end

function _substitute_bound_symbols(expr, bindings::Dict{Symbol,Any})
    if expr isa Symbol
        return get(bindings, expr, expr)
    elseif expr isa QuoteNode || expr isa LineNumberNode
        return expr
    elseif expr isa Expr
        return Expr(expr.head, (_substitute_bound_symbols(arg, bindings) for arg in expr.args)...)
    end
    return expr
end

function _inline_run_call(ctx::_ModelCompilationContext, expr::Expr, bindings::Dict{Symbol,Any}, stack::Set{Tuple{Symbol,Symbol}}, current_scale::Symbol)
    call_args = Any[_substitute_bound_symbols(arg, bindings) for arg in expr.args[2:end]]
    length(call_args) >= 4 || error("Cannot inline `run!` call with fewer than four runtime arguments: `$expr`.")
    scale, process = _resolve_model_reference(call_args[1], current_scale)
    model = _model_from_context(ctx, scale, process)
    hard_node = HardDependencyNode(
        model,
        process,
        NamedTuple(),
        Int[],
        scale,
        inputs_(model),
        outputs_(model),
        nothing,
        HardDependencyNode[]
    )
    full_args = _complete_run_call_args(call_args)
    call = _CompiledRunCall(full_args[1], full_args[2], full_args[3], full_args[4], full_args[5], full_args[6])
    return Expr(:block, _inline_model_node(ctx, hard_node, call, stack)...)
end

function _complete_run_call_args(args::Vector{Any})
    values = Any[args...]
    length(values) < 5 && push!(values, :(nothing))
    length(values) < 6 && push!(values, :(nothing))
    length(values) == 6 || error("Cannot inline `run!` call with unsupported arity $(length(args)).")
    return values
end

function _model_from_context(ctx::_ModelCompilationContext, scale::Symbol, process::Symbol)
    if ctx.models isa AbstractDict
        haskey(ctx.models, scale) || error("Cannot inline hard dependency `$(process)`: scale `$(scale)` is not in the model mapping.")
        hasproperty(ctx.models[scale], process) || error("Cannot inline hard dependency `$(process)` at scale `$(scale)`: no model found.")
        return getproperty(ctx.models[scale], process)
    end
    scale == :Default || error("Cannot inline hard dependency `$(process)` at scale `$(scale)` in a single-scale model mapping.")
    hasproperty(ctx.models, process) || error("Cannot inline hard dependency `$(process)`: no model found.")
    return getproperty(ctx.models, process)
end

function _resolve_model_reference(expr, current_scale::Symbol)
    if Meta.isexpr(expr, :.) && length(expr.args) == 2 && expr.args[2] isa QuoteNode
        process = expr.args[2].value
        scale = _resolve_models_container_scale(expr.args[1], current_scale)
        return scale, process
    end
    error("Cannot inline hard dependency call. Unsupported model reference `$expr`.")
end

function _resolve_models_container_scale(expr, current_scale::Symbol)
    expr == :models && return current_scale
    if Meta.isexpr(expr, :ref) && length(expr.args) == 2
        base, scale_expr = expr.args
        scale = _quote_value(scale_expr)
        if base == :models_by_scale || _is_sim_models_expr(base)
            scale isa Symbol || error("Cannot inline hard dependency call. Expected a literal scale symbol in `$expr`.")
            return scale
        end
    end
    error("Cannot inline hard dependency call. Unsupported models container `$expr`.")
end

function _quote_value(expr)
    expr isa QuoteNode && return expr.value
    expr isa Symbol && return expr
    return nothing
end

function _is_sim_models_expr(expr)
    return Meta.isexpr(expr, :.) &&
           length(expr.args) == 2 &&
           expr.args[1] == :sim &&
           expr.args[2] == QuoteNode(:models)
end

_is_run_function(f) = f == :run! || f == GlobalRef(@__MODULE__, :run!)
function _is_run_function(f::Expr)
    return Meta.isexpr(f, :.) &&
           length(f.args) == 2 &&
           f.args[1] in (:PlantSimEngine, Symbol(@__MODULE__)) &&
           f.args[2] == QuoteNode(:run!)
end

function _models_process_symbol(expr)
    if Meta.isexpr(expr, :.) && length(expr.args) == 2 && expr.args[1] == :models && expr.args[2] isa QuoteNode
        return (:Default, expr.args[2].value)
    end
    return nothing
end

function _strip_return_expr(expr)
    if Meta.isexpr(expr, :return)
        return length(expr.args) == 0 ? nothing : expr.args[1]
    elseif Meta.isexpr(expr, :block)
        args = Any[]
        for (i, arg) in enumerate(expr.args)
            if Meta.isexpr(arg, :return)
                i == length(expr.args) || error("Cannot inline model body with a non-final top-level `return`.")
                stripped = _strip_return_expr(arg)
                !isnothing(stripped) && push!(args, stripped)
            else
                _contains_return(arg) && error("Cannot inline model body with a nested `return`.")
                push!(args, arg)
            end
        end
        return Expr(:block, args...)
    end
    return expr
end

function _contains_return(expr)
    Meta.isexpr(expr, :return) && return true
    expr isa Expr || return false
    return any(_contains_return, expr.args)
end

function _block_statements(expr)
    isnothing(expr) && return Any[]
    Meta.isexpr(expr, :block) && return Any[expr.args...]
    return Any[expr]
end

function _sprint_expr(expr)
    io = IOBuffer()
    Base.show_unquoted(io, expr, 0, 0)
    return String(take!(io))
end
